AdminSide/Areas/PlatformManagement/Controllers/ChallengeServersController.cs
using AdminSide.Areas.PlatformManagement.Data;
using AdminSide.Areas.PlatformManagement.Models;
using AdminSide.Areas.PlatformManagement.Services;
using Amazon.CloudWatch;
using Amazon.CloudWatch.Model;
using Amazon.EC2;
using Amazon.EC2.Model;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Transfer;
using ASPJ_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Protocol = AdminSide.Areas.PlatformManagement.Models.Protocol;
using State = AdminSide.Areas.PlatformManagement.Models.State;
using Subnet = AdminSide.Areas.PlatformManagement.Models.Subnet;
using Tag = Amazon.EC2.Model.Tag;
using Tenancy = AdminSide.Areas.PlatformManagement.Models.Tenancy;

namespace AdminSide.Areas.PlatformManagement.Controllers
{
    [Area("PlatformManagement")]
    [Authorize]
    public class ChallengeServersController : Controller
    {
        private readonly PlatformResourcesContext _context;

        private IAmazonEC2 EC2Client { get; set; }

        private IAmazonS3 S3Client { get; set; }

        private IAmazonCloudWatch CWClient { get; set; }

        private ChallengeServersCreationFormModel creationReference;

        private readonly IApplicationLifetime _appLifetime;
        private readonly ILogger _logger;

        public IBackgroundTaskQueue Backgroundqueue { get; }

        public ChallengeServersController(PlatformResourcesContext context, IAmazonEC2 ec2Client, IBackgroundTaskQueue Queue, IApplicationLifetime appLifetime, ILogger<ChallengeServersController> logger, IAmazonCloudWatch CWClient)
        {
            this._context = context;
            this.EC2Client = ec2Client;
            AmazonS3Config config = new AmazonS3Config
            {
                ForcePathStyle = true
            };
            this.S3Client = new AmazonS3Client(config);
            Backgroundqueue = Queue;
            _appLifetime = appLifetime;
            _logger = logger;
            this.CWClient = CWClient;
        }

        public async Task<IActionResult> Index()
        {
            if (_context.VPCs.ToList().Count == 0)
            {
                return RedirectToAction("", "Home", "");
            }
            return View(await _context.Servers.ToListAsync());
        }

        public async Task<IActionResult> SelectTemplate()
        {
            if (_context.VPCs.ToList().Count == 0)
            {
                return RedirectToAction("", "Home", "");
            }
            return View(await _context.Templates.ToListAsync());
        }

        public IActionResult SpecifySettings()
        {
            if (_context.VPCs.ToList().Count == 0)
            {
                return RedirectToAction("", "Home", "");
            }
            return RedirectToAction("SelectTemplate");
        }

        public IActionResult VerifySettings()
        {
            if (_context.VPCs.ToList().Count == 0)
            {
                return RedirectToAction("", "Home", "");
            }
            if (creationReference == null)
            {
                return RedirectToAction("SelectTemplate");
            }
            else
            {
                return View(creationReference);
            }
        }

        public async Task<IActionResult> RedirectServerCreation(String selectedTemplate)
        {
            if (_context.VPCs.ToList().Count == 0)
            {
                return RedirectToAction("", "Home", "");
            }
            if (selectedTemplate != null)
            {
                Template selected = await _context.Templates.FindAsync(int.Parse(selectedTemplate));
                if (selected != null)
                {
                    return await SpecifySettings(Convert.ToString(selected.ID));
                }
                else
                {
                    return RedirectToAction("", "ServerTemplates", "");
                }
            }
            else
            {
                return RedirectToAction("", "ServerTemplates", "");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Credentials(string serverID)
        {
            Server selected = await _context.Servers.FindAsync(int.Parse(serverID));
            if (selected != null)
            {
                ChallengeServersCredentialsPageModel model = new ChallengeServersCredentialsPageModel();
                model.serverName = selected.Name;
                model.serverIP = selected.IPAddress;
                model.serverDNS = selected.DNSHostname;
                String keyPairString = null;
                TransferUtility fileTransferUtility = new TransferUtility(S3Client);
                fileTransferUtility.Download(@"C:\Tempt\" + selected.KeyPairName + ".pem", "ectf-keypair", selected.KeyPairName + ".pem");
                using (FileStream fileDownloaded = new FileStream(@"C:\Tempt\" + selected.KeyPairName + ".pem", FileMode.Open, FileAccess.Read))
                {
                    using (StreamReader reader = new StreamReader(fileDownloaded))
                    {
                        keyPairString = reader.ReadToEnd();
                    }
                }
                System.IO.File.Delete(@"C:\Tempt\" + selected.KeyPairName + ".pem");
                if (selected.OperatingSystem.Contains("Windows"))
                {
                    model.Windows = true;
                    GetPasswordDataResponse response = await EC2Client.GetPasswordDataAsync(new GetPasswordDataRequest
                    {
                        InstanceId = selected.AWSEC2Reference
                    });
                    if (String.IsNullOrEmpty(response.PasswordData))
                    {
                        model.Available = false;
                    }
                    else
                    {
                        model.retrievedPassword = response.GetDecryptedPassword(keyPairString);
                        model.Available = true;
                    }
                }
                else
                {
                    model.keyPairDownloadURL = S3Client.GetPreSignedURL(new GetPreSignedUrlRequest
                    {
                        BucketName = "ectf-keypair",
                        Key = selected.KeyPairName + ".pem",
                        Expires = DateTime.Now.AddMinutes(5),
                        Protocol = Amazon.S3.Protocol.HTTPS,
                        ResponseHeaderOverrides = new ResponseHeaderOverrides
                        {
                            ContentDisposition = "attachement"
                        }
                    });
                }
                return View(model);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]

        public async Task<IActionResult> SpecifySettings(String selectedTemplate)
        {
            if (selectedTemplate != null)
            {
                Template selected = await _context.Templates.FindAsync(int.Parse(selectedTemplate));
                if (selected != null)
                {
                    ViewData["selectedTemplate"] = selected.ID;
                    if (selected.SpecificMinimumSize == true)
                    {
                        ViewData["minimumSize"] = selected.MinimumStorage;
                    }
                    else
                    {
                        ViewData["minimumSize"] = 8;
                    }

                    return View(await _context.Subnets.ToListAsync());
                }
                else
                {
                    return NotFound();
                }
            }
            else
            {
                return RedirectToAction("SelectTemplate");
            }
        }

        [HttpPost]

        public async Task<IActionResult> VerifySettings(String ServerName, String ServerWorkload, String SelectedTemplate, String ServerStorage, String ServerTenancy, String ServerSubnet)
        {
            creationReference = new ChallengeServersCreationFormModel
            {
                ServerName = ServerName,
                ServerWorkload = ServerWorkload,
                selectedTemplate = await _context.Templates.FindAsync(Int32.Parse(SelectedTemplate)),
                ServerStorage = Int32.Parse(ServerStorage),
                ServerTenancy = ServerTenancy,
                ServerSubnet = await _context.Subnets.FindAsync(Int32.Parse(ServerSubnet))
            };
            TempData["TemplateID"] = creationReference.selectedTemplate.ID;
            TempData["SubnetID"] = creationReference.ServerSubnet.ID;
            return View(creationReference);
        }

        [HttpPost]

        public async Task<IActionResult> Submission([Bind("TemplateName,OperatingSystem,ServerName,ServerWorkload,ServerStorage,ServerTenancy,SubnetCIDR,TemplateID,SubnetID")] ChallengeServersCreationFormModel Model2)
        {
            Template selectedT = await _context.Templates.FindAsync(Int32.Parse(Model2.TemplateID));
            Subnet selectedS = await _context.Subnets.FindAsync(Int32.Parse(Model2.SubnetID));
            Guid g = Guid.NewGuid();
            string randomKeypairString = Convert.ToBase64String(g.ToByteArray());
            randomKeypairString = randomKeypairString.Replace("=", "");
            randomKeypairString = randomKeypairString.Replace("+", "");
            randomKeypairString = randomKeypairString.Replace("\\", "");
            randomKeypairString = randomKeypairString.Replace("/", "");
            CreateKeyPairResponse responseCreateKeyPair = await EC2Client.CreateKeyPairAsync(new CreateKeyPairRequest
            {

AdminSide/Areas/PlatformManagement/Views/ChallengeServers/ModifyServer.cshtml
@model AdminSide.Areas.PlatformManagement.Models.Server

@{
    ViewData["Title"] = "Modify Server";
}
<h2>Modify</h2>
<h4>Subnet</h4>
<hr />
@if (!String.IsNullOrEmpty(Convert.ToString(TempData["Result"])))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-danger" role="alert">
                @TempData["Result"]
            </div>
        </div>
    </div>
}
@if (!String.IsNullOrEmpty(Convert.ToString(TempData["Exception"])))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-danger" role="alert">
                @TempData["Exception"]
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-lg-6 border-right">
        <form asp-action="Modification" method="post" class="needs-validation" novalidate>
            <h3>Server Settings</h3>
            <div class="form-group">
                <label for="ServerName">Server Name:</label>
                <input type="text" class="form-control" id="ServerName" name="ServerName" value="@Model.Name" pattern="^[A-Za-z0-9 _-]*[A-Za-z0-9][A-Za-z0-9 _ -]*$" required>
                <div class="invalid-feedback">A server needs a alphanumeric name</div>
            </div>
            <input type="hidden" id="ServerIDSrc" name="ID" value="@Model.ID" />
            <div class="form-group">
                <label for="OperatingSystem">Operating System:</label>
                <input type="text" disabled class="form-control-plaintext" id="OperatingSystem" name="OperatingSystem" value="@Html.ValueForModel(Model.OperatingSystem)" />
            </div>
            <div class="form-group">
                <label for="ServerWorkload">Server Workload</label>
                <select class="form-control" id="ServerWorkload" name="ServerWorkload" required>
                    @if (Model.Workload == Workload.Low)
                    {
                        <option value="Low" selected>Low</option>
                        <option value="Medium">Medium</option>
                        <option value="Large">Large</option>
                    }
                    @if (Model.Workload == Workload.Medium)
                    {
                        <option value="Low">Low</option>
                        <option value="Medium" selected>Medium</option>
                        <option value="Large">Large</option>
                    }
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="Large">Large</option>
                </select>
                <div class="invalid-feedback">Server's Workload must be selected</div>
            </div>
            <div class="form-group">
                <label for="ServerStorage">Server Assigned Storage:</label>
                <input type="number" class="form-control" id="ServerStorage" name="ServerStorage" value="@Model.StorageAssigned" min="@Model.StorageAssigned" max="1000" placeholder="Size in Gigabytes" required>
                <div class="invalid-feedback">You cannot assign a lower storage space to your server!</div>
            </div>
            <div class="form-group">
                <label>Server Tenancy:</label>
                @if (Model.Tenancy == Tenancy.Shared)
                {
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyS" value="Shared" checked required>
                        <label class="form-check-label" for="ServerTenancyS">Shared</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDI" value="Dedicated Instance">
                        <label class="form-check-label" for="ServerTenancyDI">Dedicated Instance</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDH" value="Dedicated Hardware">
                        <label class="form-check-label" for="ServerTenancyDH">Dedicated Hardware</label>
                        <div class="invalid-feedback">Select the server's tenancy</div>
                    </div>
                }
                @if (Model.Tenancy == Tenancy.DedicatedInstance)
                {
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyS" value="Shared" required>
                        <label class="form-check-label" for="ServerTenancyS">Shared</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDI" value="Dedicated Instance" checked>
                        <label class="form-check-label" for="ServerTenancyDI">Dedicated Instance</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDH" value="Dedicated Hardware">
                        <label class="form-check-label" for="ServerTenancyDH">Dedicated Hardware</label>
                        <div class="invalid-feedback">Select the server's tenancy</div>
                    </div>
                }
                @if (Model.Tenancy == Tenancy.DedicatedHardware)
                {
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyS" value="Shared" required>
                        <label class="form-check-label" for="ServerTenancyS">Shared</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDI" value="Dedicated Instance">
                        <label class="form-check-label" for="ServerTenancyDI">Dedicated Instance</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDH" value="Dedicated Hardware" checked>
                        <label class="form-check-label" for="ServerTenancyDH">Dedicated Hardware</label>
                        <div class="invalid-feedback">Select the server's tenancy</div>
                    </div>
                }
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary float-right">Save Changes</button>
            </div>
        </form>
    </div>
    <div class="col-lg-6 border-left">
        <h3>Network Settings</h3>
        <div class="form-group">
            <label for="ServerSubnet">Server Subnet: </label>
            <input type="text" disabled class="form-control-plaintext" id="ServerSubnet" name="SubnetCIDR" value="@Html.ValueForModel(Model.LinkedSubnet.Name) (@Html.ValueForModel(Model.LinkedSubnet.IPv4CIDR) / @Html.ValueForModel(Model.LinkedSubnet.IPv6CIDR))" />
        </div>
        <div class="form-group">
            <p class="form-text">Server Firewall Rules</p>
            <form asp-action="CreateFirewallRule" method="get">
                <input type="hidden" id="ServerIDDest" name="ServerID" value="" />
                <button type="submit" class="btn btn-secondary float-right">Add Rule</button>
            </form>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Direction</th>
                        <th scope="col">Type</th>
                        <th scope="col">Protocol</th>
                        <th scope="col">Port</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Incoming and Outgoing Traffic</td>
                        <td>IMPLICT-DENY</td>
                        <td>TCP and UDP</td>
                        <td>All Ports not listed below</td>
                        <td>You can't edit/remove this rule</td>
                    </tr>
                    @foreach (var rule in Model.FirewallRules)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => rule.Direction)</td>
                            <td>@Html.DisplayFor(modelItem => rule.Type)</td>
                            <td>@Html.DisplayFor(modelItem => rule.Protocol)</td>
                            <td>@Html.DisplayFor(modelItem => rule.Port)</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <form asp-action="DeleteFirewallRule" method="post">
                                        <input type="hidden" name="ID" value="@rule.ID" />
                                        <button type="submit" class="btn btn-danger">Delete Rule</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <button type="button" class="btn btn-secondary float-left" data-toggle="modal" data-target="#confirmationModal">Go back</button>
    </div>
</div>

<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure that you want to go back? All current entries will be lost!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <a asp-area="PlatformManagement" asp-controller="ChallengeServers" asp-action="" class="btn btn-primary">Yes</a>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
        var serverID = document.getElementById('ServerIDSrc').value;
        document.getElementById('ServerIDDest').value = serverID;
    </script>
}

AdminSide/Areas/PlatformManagement/Views/ChallengeServers/SpecifySettings.cshtml
@model IEnumerable<AdminSide.Areas.PlatformManagement.Models.Subnet>

@{
    ViewData["Title"] = "Create Server - Specify Settings";
}

<ul class="progress-tracker progress-tracker--text progress-tracker--center">
    <li class="progress-step is-complete">
        <span class="progress-marker"></span>
        <span class="progress-text">
            <h4 class="progress-title">Step 1</h4>
            Choose Server Template
        </span>
    </li>
    <li class="progress-step is-active">
        <span class="progress-marker"></span>
        <span class="progress-text">
            <h4 class="progress-title">Step 2</h4>
            Specify Server Settings
        </span>
    </li>
    <li class="progress-step">
        <span class="progress-marker"></span>
        <span class="progress-text">
            <h4 class="progress-title">Step 3</h4>
            Verify Settings
        </span>
    </li>
    <li class="progress-step">
        <span class="progress-marker"></span>
        <span class="progress-text">
            <h4 class="progress-title">Step 4</h4>
            Launch Server
        </span>
    </li>
</ul>
<div class="alert alert-warning" role="alert">
    Do not refresh this page or you will restart at step 1
</div>
<form asp-action="VerifySettings" method="post" class="needs-validation" novalidate>
    <div class="row">
        <div class="col-lg-6 border-right">
            <h3>Server Settings</h3>
            <div class="form-group">
                <label for="ServerName">Server Name:</label>
                <input type="text" class="form-control" id="ServerName" name="ServerName" pattern="^[A-Za-z0-9 _-]*[A-Za-z0-9][A-Za-z0-9 _ -]*$" required>
                <div class="invalid-feedback">A server needs a alphanumeric name</div>
            </div>
            <div class="form-group">
                <label for="ServerWorkload">Server Workload</label>
                <select class="form-control" id="ServerWorkload" name="ServerWorkload" required>
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="Large">Large</option>
                </select>
                <div class="invalid-feedback">Server's Workload must be selected</div>
            </div>
            <input type="hidden" name="selectedTemplate" value="@ViewData["selectedTemplate"]" />
            <div class="form-group">
                <label for="ServerStorage">Server Assigned Storage:</label>
                <input type="number" class="form-control" id="ServerStorage" name="ServerStorage" min="@ViewData["minimumSize"]" max="1000" placeholder="Size in Gigabytes" required>
                <div class="invalid-feedback">A minimum Storage space of @ViewData["minimumSize"] Gigabytes must be assigned to the server</div>
            </div>
            <div class="form-group">
                <label>Server Tenancy:</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyS" value="Shared" required>
                    <label class="form-check-label" for="ServerTenancyS">Shared</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDI" value="Dedicated Instance">
                    <label class="form-check-label" for="ServerTenancyDI">Dedicated Instance</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ServerTenancy" id="ServerTenancyDH" value="Dedicated Hardware">
                    <label class="form-check-label" for="ServerTenancyDH">Dedicated Hardware</label>
                    <div class="invalid-feedback">Select the server's tenancy</div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 border-left">
            <h3>Network Settings</h3>
            <div class="form-group">
                <label for="Subnet">Server Subnet: </label>
                <select class="form-control" id="Subnet" name="ServerSubnet" required>
                    @foreach (var subnet in Model)
                    {
                        <option aria-type="@subnet.Type" value="@subnet.ID">@subnet.Name (@subnet.IPv4CIDR / @subnet.IPv6CIDR)</option>
                    }
                </select>
                <div class="invalid-feedback">Please select a subnet</div>
            </div>
            <div class="form-group">
                <p class="form-text">Server Firewall Rules</p>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Direction</th>
                            <th scope="col">Type</th>
                            <th scope="col">Protocol</th>
                            <th scope="col">Port</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="4">You can whitelist ports when the server has been launched</td>
                        </tr>
                        <tr>
                            <td>Incoming and Outgoing Traffic</td>
                            <td>IMPLICT-DENY</td>
                            <td>TCP and UDP</td>
                            <td>All Ports not listed above</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <button type="button" class="btn btn-secondary float-left" data-toggle="modal" data-target="#confirmationModal">Go back and select a new template</button>
            <button type="submit" class="btn btn-primary float-right">Continue</button>
        </div>
    </div>
</form>
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure that you want to go back to select a new template? All current entries will be lost!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <a asp-area="PlatformManagement" asp-controller="ChallengeServers" asp-action="SelectTemplate" class="btn btn-primary">Yes</a>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
        document.getElementById("ServerWorkload").selectedIndex = -1;
        document.getElementById("Subnet").selectedIndex = -1;
    </script>
}